config/routes.rb
# -*- encoding : utf-8 -*-

require 'api_constraints'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  #########################################
  ############## Aplicação ################
  #########################################
  namespace :a do
    devise_for :usuarios, class_name: "Usuario", controllers: { sessions: 'a/usuarios/sessions',
                                                                passwords: 'a/usuarios/passwords',
                                                                registrations: 'a/usuarios'  }
    controller :usuarios do
      get "usuarios/alterar_senha" => :alterar_senha
      post "usuarios/salvar_senha" => :salvar_senha
    end
    resources :usuarios

    controller :contatos do
      get '/contatos/facebook' => :facebook, as: :contatos_facebook
    end
    resources :contatos


    controller :configuracoes do
      get '/configuracoes/gerais' => :gerais, as: :configuracoes_gerais
      post '/configuracoes/gerais_salvar' => :gerais_salvar, as: :configuracoes_gerais_salvar
      get '/configuracoes/sobre' => :sobre, as: :configuracoes_sobre
      post '/configuracoes/sobre_salvar' => :sobre_salvar, as: :configuracoes_sobre_salvar
      get 'configuracoes/gerar_api_token' => :gerar_api_token
    end

    root "contatos#index"
  end

  #########################################
  ################ Public #################
  #########################################

  controller :contatos do
  end
  resources :contatos

  controller :pages do
    get '/home' => :home
  end

  root "pages#home"

  #########################################
  ################# API ###################
  #########################################
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      controller :sync do
        get 'sync' => :sync
      end

    end
  end

end

app/views/template/_alert.html.erb
<div class="alert fade in alert-<%= type.blank? ? 'info' : type.to_s %>">
  <button data-dismiss="alert" class="close">×</button>
  <%= notice.html_safe %>
</div>

<script type="text/javascript">
  // Remove mensagem alert depois de 3 segundos
  <% if defined?(keep).nil? %>
    setTimeout(function(){deleteSystemNotice()}, 3000);
  <% end %>
</script>

<%# type = [success, info, warning, danger] %>
<%# Padrão é: info %>

app/views/template/_autocomplete_remote_tag.html.erb
<script type="text/javascript">
  $(function() {
    $('<%= dom_element %>').autocomplete({
        minLength: 1,
        source: function(request, response) {
          $.ajax({
            url: '<%= source_path %>',
            dataType: 'json',
            data: {
              term: request.term,
              <% if defined? additional_params %>
                <%= additional_params.collect{|key, value| "#{key.to_s}: $(\"##{value.to_s}\").val()".html_safe}.join(',').html_safe %>
              <% end %>
            },
            beforeSend: function() {
              $('<%= dom_element %>').addClass('loader');
            },
            success: function(data) {
              $('<%= dom_element %>').removeClass('loader');
              response($.map(data, function(item) {
                return {
                  label: item.label,
                  value: item.value
                }
              }));
            }
          });
        },
        focus: function( event, ui ) {
          $( '<%= dom_element %>' ).val( ui.item.label );
          return false;
        },
        select: function( event, ui ) {
          $( '<%= dom_element %>' ).val( ui.item.label );
          $( '<%= dom_element_id %>' ).val( ui.item.value ).trigger('change');
          return false;
        }
    });

    $(document).on('blur', "<%= dom_element %>", function() {
      if($(this).val() == "" ) {
        $('<%= dom_element_id %>').val("").trigger('change');
      }
    });

  });

</script>

app/views/template/_current_a_usuario.html.erb
<li class="dropdown">

  <%= link_to '#', class: "dropdown-toggle ", 'data-toggle' => "dropdown" do %>
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span><%= current_a_usuario.nome %> <b class="caret"></b>
  <% end %>

  <ul class="dropdown-menu">
    <% if can? :show, current_a_usuario %>
      <%= menu_item "#{glyph('user', {tag: :span})} #{current_a_usuario.nome}".html_safe, a_usuario_path(current_a_usuario), data: { toggle: 'modal', target: '#modal-element' } %>
    <% end %>
    <% if can? :alterar_senha, current_a_usuario %>
      <%= menu_item "#{glyph('lock', {tag: :i})} #{t('usuarios.password_change_link')}".html_safe, a_usuarios_alterar_senha_path(id: current_a_usuario.to_param), data: { toggle: 'modal', target: '#modal-element' } %>
    <% end %>

  </ul>
    <%= menu_item "#{glyph('log-out', {tag: :span})} Logout".html_safe, "/a/usuarios/sign_out", method: :delete %>
</li>

app/views/template/_form_error.html.erb
<% if object.errors.any? %>
  <div id="error_expl" class="panel panel-roxo">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(object.errors.count, "Erro") %></h3>
    </div>
    <div class="panel-body">
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/template/_menu.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
      <!-- Menu mobile -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu">
        <span class="glyphicon glyphicon-log-out"></span>
      </button>
      <!-- Brand -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menubar" style="float: left;">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="main-menu" style="float: right;">


      <!-- Menu de usuário -->
      <% if current_a_usuario %>
        <ul class="nav navbar-nav navbar-right">
          <%= render '/template/current_a_usuario' unless current_a_usuario.blank? %>
        </ul>
      <% end %>
    </div>

  </div>
</nav>

app/views/template/_menubar.html.erb
<div id="menubar" class="collapse navbar-collapse menubar" style="background-color: #EDEDED;">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel-group" id="accordion">
                    <div class="panel panel-default" style="margin-bottom: 5px;">
                <%= link_to a_root_path do %>
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <span class="glyphicon glyphicon-home">
                                </span>Home
                            </h4>
                        </div>
                <% end %>
                    </div>

                <div class="panel panel-default"><a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-user">
                            </span>Usuários
                        </h4>
                    </div></a>
                    <div id="collapseTwo" class="panel-collapse collapse <%= (%w(a/usuarios a/contatos).include?(params[:controller])) ? 'in' : '' %>">
                        <div class="panel-body">
                            <table class="table">

                                <% if can? :index, Usuario or can? :create, Usuario %>
                                <tr>
                                    <td class="<%= (%w(a/usuarios).include?(params[:controller])) ? 'active' : '' %>">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                        <%= link_to "Administradores Backend", a_usuarios_path %>
                                    </td>
                                </tr>
                                <% end %>
                                <tr>
                                    <td class="<%= (%w(facebook ).include?(params[:action])) ? 'active' : '' %>">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                        <%= link_to "Facebook", a_contatos_facebook_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="<%= (%w(index ).include?(params[:action])) ? 'active' : '' %>">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                        <%= link_to "Site", a_contatos_path %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default"><a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-cog">
                            </span>Configurações
                        </h4>
                    </div></a>
                    <div id="collapseSix" class="panel-collapse collapse <%= (%w(a/configuracoes ).include?(params[:controller])) ? 'in' : '' %>">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td class="<%= (%w(gerais ).include?(params[:action])) ? 'active' : '' %>">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                        <%= link_to "Geral", a_configuracoes_gerais_path %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                <%= link_to root_path, :target => '_blank' do %>
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-fullscreen">
                            </span>Site - Visualizar
                        </h4>
                    </div>
                <% end %>
                </div>
            </div>
        </div>
    </div>
</div>


<style type="text/css">
    .menubar .panel-body .table tr > td.active a{
        color: #337AB7;
    }
    .menubar .panel-body .table tr > td.active span{
        color: #337AB7;
    }
    span.badge{
        float: right;
    }

</style>

app/views/template/_modal_header.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only">Close</span>
  </button>
  <h4 class="modal-title" id="modal-element-label"><%= t('.title', default: title).html_safe %></h4>
</div>