config/routes.rb
# -*- encoding : utf-8 -*-

require 'api_constraints'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  #########################################
  ############## Aplicação ################
  #########################################
  namespace :a do
    devise_for :usuarios, class_name: "Usuario", controllers: { sessions: 'a/usuarios/sessions',
                                                                passwords: 'a/usuarios/passwords',
                                                                registrations: 'a/usuarios'  }
    controller :usuarios do
      get "usuarios/alterar_senha" => :alterar_senha
      post "usuarios/salvar_senha" => :salvar_senha
    end
    resources :usuarios

    controller :contatos do
      get '/contatos/facebook' => :facebook, as: :contatos_facebook
    end
    resources :contatos


    controller :configuracoes do
      get '/configuracoes/gerais' => :gerais, as: :configuracoes_gerais
      post '/configuracoes/gerais_salvar' => :gerais_salvar, as: :configuracoes_gerais_salvar
      get '/configuracoes/sobre' => :sobre, as: :configuracoes_sobre
      post '/configuracoes/sobre_salvar' => :sobre_salvar, as: :configuracoes_sobre_salvar
      get 'configuracoes/gerar_api_token' => :gerar_api_token
    end

    root "contatos#index"
  end

  #########################################
  ################ Public #################
  #########################################

  controller :contatos do
  end
  resources :contatos

  controller :pages do
    get '/home' => :home
  end

  root "pages#home"

  #########################################
  ################# API ###################
  #########################################
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      controller :sync do
        get 'sync' => :sync
      end

    end
  end

end

app/models/contato.rb
# -*- encoding : utf-8 -*-
class Contato < ActiveRecord::Base

  validates :nome, :email, :cidade, :origem, :capital_disponivel, :telefone, presence: true

  belongs_to :estado

  scope :ordenados, -> {order('contatos.created_at ASC')}
  scope :nao_lidos, -> {where('contatos.lido_em IS NULL')}

  def codigo_to_s
    "#{self.id}"
  end

  def self.to_select
    Contato.ordenados.collect { |u| [u.nome, u.id] }
  end

  def self.to_select_cidade estado
    Cidade.where(estado_id: estado.id).collect { |u| [u.nome, u.nome] }
  end

  def self.to_select_origem
    [
      ["Linkedin", "Linkedin"],
      ["Recebeu Ligação", "Recebeu Ligação"],
      ["Recebeu Mensagem", "Recebeu Mensagem"],
      ["E-mail / Marketing", "E-mail / Marketing"],
      ["Google", "Google"],
      ["Facebook", "Facebook"],
      ["YouTube", "YouTube"],
      ["Twitter", "Twitter"],
      ["Feiras", "Feiras"]
    ]
  end

  def self.to_select_capital
    [
      ["Até R$ 50.000,00", "Até R$ 50.000,00"],
      ["De R$ 50.000,00 Até 100.000,00", "De R$ 50.000,00 Até 100.000,00"],
      ["De R$ 100.000,00 Até 150.000,00", "De R$ 100.000,00 Até 150.000,00"],
      ["De R$ 150.000,00 Até 200.000,00", "De R$ 150.000,00 Até 200.000,00"],
      ["De R$ 200.000,00 Até 250.000,00", "De R$ 200.000,00 Até 250.000,00"],
      ["De R$ 250.000,00 Até 300.000,00", "De R$ 250.000,00 Até 300.000,00"],
      ["De R$ 300.000,00 Até 350.000,00", "De R$ 300.000,00 Até 350.000,00"],
      ["De R$ 350.000,00 Até 400.000,00", "De R$ 350.000,00 Até 400.000,00"],
      ["De R$ 400.000,00 Até 450.000,00", "De R$ 400.000,00 Até 450.000,00"],
      ["De R$ 450.000,00 Até 500.000,00", "De R$ 450.000,00 Até 500.000,00"],
      ["Acima de R$ 500.000,00", "Acima de R$ 500.000,00"]
    ]
  end


  def self.media_dia data
      inicio = data.beginning_of_day
      fim = data.beginning_of_day + 1.day
      contatos = Contato.where('created_at BETWEEN ? AND ?', inicio.to_s(:db), fim.to_s(:db)).size
  end
  
end

app/controllers/a/app_controller.rb
# -*- encoding : utf-8 -*-
class A::AppController < ApplicationController

  before_action :authenticate_a_usuario!
  before_filter :guardar_per_page

  check_authorization
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: I18n.t('login.access_denied')
  end

  # Define o usuario a ser tertado no ability.rb
  def current_ability
    @current_ability ||= Ability.new(current_a_usuario)
  end

  private
    #
    # Uma vez que se altere o per_page, ele vai pra sessão.
    # Isso facilita buscas globais e não perde o per_page em listas com filtros.
    def guardar_per_page
      if params[:per_page].blank?
        params[:per_page] = session[:per_page]
      else
        session[:per_page] = params[:per_page]
      end
    end

end

app/controllers/a/configuracoes_controller.rb
# -*- encoding : utf-8 -*-
class A::ConfiguracoesController < A::AppController

  skip_authorization_check
  skip_load_and_authorize_resource

  before_filter :garantir_autorizacao



  def gerais_salvar

    # CONFIGURACOES
    Settings['CONFIGURACOES.title']                                 = params[:title]
    Settings['CONFIGURACOES.logo']                                  = params[:logo]
    Settings['CONFIGURACOES.logo2']                                 = params[:logo2]
    Settings['CONFIGURACOES.logo_after']                            = params[:logo_after]
    Settings['CONFIGURACOES.logo2_after']                           = params[:logo2_after]

    # CONTATO
    Settings['CONTATO.telefone']            = params[:telefone]
    Settings['CONTATO.email']               = params[:email]
    Settings['CONTATO.mensagem']            = params[:mensagem]
    Settings['CONTATO.endereco']            = params[:endereco]
    Settings['CONTATO.atendimento_online']  = params[:atendimento_online]
    Settings['CONTATO.mapa_iframe']         = params[:mapa_iframe]

    # REDE_SOCIAIS
    Settings['REDE_SOCIAIS.site']       = params[:site]
    Settings['REDE_SOCIAIS.facebook']   = params[:facebook]

    @system_notice = I18n.t('configuracoes.salvou')
    @type = 'success'

    redirect_to a_configuracoes_gerais_path, notice: @system_notice
  end

  def gerar_api_token
    ApiKey.first.destroy
    ApiKey.create!

    respond_to do |format|
      format.js
    end
  end

  private

    def garantir_autorizacao
      authorize! :configurar, :sistema
    end

end

app/controllers/a/contatos_controller.rb
# -*- encoding : utf-8 -*-
class A::ContatosController < A::AppController

  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  def index
    conditions = []
    conditions << "contatos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "contatos.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    conditions << "contatos.pre_cadastro IS NULL"

    @contatos = Contato.where(conditions.join(' AND ')).ordenados.paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @contatos.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('contatos.contatos'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contatos
  def facebook
    conditions = []
    conditions << "contatos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "contatos.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    @contatos = Contato.where(conditions.join(' AND ')).where(pre_cadastro: true).ordenados.paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @contatos.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('contatos.contatos'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contatos/1
  def show
    @reduzir = false
    if @contato.lido_em.nil?
      @contato.lido_em = Time.zone.now
      @contato.save(:validate => false)
      @reduzir = true
    end
    render layout: false
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # contato /contatos
  def create
    @contato = Contato.new(contato_params)

    if @contato.save
      redirect_to a_contatos_path, notice: "Contato Criado!"
    else
      render :new
    end
  end

  # PATCH/PUT /contatos/1
  def update

    if @contato.update(contato_params)
      redirect_to a_contatos_path, notice: "Contato Atualizado!"
    else
      render :edit
    end
  end

  # DELETE /contatos/1
  def destroy
    @contato.destroy
    redirect_to a_contatos_url, notice: notice
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contato_params
      params.require(:contato).permit(:nome, :telefone, :email, :mensagem, :capital_disponivel, :cidade, :origem)
    end

end

app/controllers/a/usuarios/passwords_controller.rb
# -*- encoding : utf-8 -*-
class A::Usuarios::PasswordsController < Devise::PasswordsController

  # layout false, only: [:new, :create]
  # layout 'site', only: [:edit, :update]

  layout :layout_by_resource

  protected

  def after_sending_reset_password_instructions_path_for(resource_name)
    new_a_usuario_session_path
  end

  def layout_by_resource
    if devise_controller? && (action_name == "new" or action_name == "create")
      false
    else
      "application"
    end
  end

end

app/controllers/a/usuarios/sessions_controller.rb
# -*- encoding : utf-8 -*-
class A::Usuarios::SessionsController < Devise::SessionsController
end

app/controllers/a/usuarios_controller.rb
# -*- encoding : utf-8 -*-
class A::UsuariosController < A::AppController

  before_action :set_usuario, only: [:show, :edit, :update, :destroy, :alterar_senha]

  # GET /usuarios
  def index
    conditions = []
    conditions << "usuarios.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "usuarios.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    params[:ativos] = true if params[:ativos].blank?
    conditions << "usuarios.ativo = #{params[:ativos]}"

    @usuarios = Usuario.where(conditions.join(' AND ')).order("nome ASC").paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @usuarios.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('usuarios.usuarios'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /usuarios/1
  def show
    render layout: false
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # usuario /usuarios
  def create
    @usuario = Usuario.new(usuario_params)

    if @usuario.save
      redirect_to a_usuarios_path, notice: I18n.t('action_controller.adicionado', model: I18n.t('usuarios.usuario'))
    else
      render :new
    end
  end

  # PATCH/PUT /usuarios/1
  def update

    # Se o password não foi preenchido, não atualiza
    if params[:usuario][:password].blank?
      params[:usuario].delete :password
      params[:usuario].delete :password_confirmation
    end

    if @usuario.update(usuario_params)
      redirect_to a_usuarios_path, notice: I18n.t('action_controller.atualizado', model: I18n.t('usuarios.usuario'))
    else
      render :edit
    end
  end

  # DELETE /usuarios/1
  def destroy
    @usuario.alterar!
    @usuario.ativo? ? (notice = I18n.t('action_controller.ativado', model: I18n.t('usuarios.usuario'))) : (notice = I18n.t('action_controller.desativado', model: I18n.t('usuarios.usuario')))
    redirect_to a_usuarios_url, notice: notice
  end

  def alterar_senha
    render layout: false
  end

  def salvar_senha
    @usuario = current_a_usuario

    senha_valida = @usuario.valid_password? params[:usuario][:password_atual]
    @usuario.errors.add(:password_atual, I18n.t('usuarios.password_invalida')) unless senha_valida

    respond_to do |format|
      if senha_valida and @usuario.update(usuario_params)
        sign_in(current_a_usuario, bypass: true)
        @system_notice = I18n.t('action_controller.atualizada', model: I18n.t('usuarios.password'))
        @type = 'info'
        format.js
      else
        format.js
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def usuario_params
      params.require(:usuario).permit(:nome, :telefone, :celular, :email, :password, :password_confirmation, :ativo, :super_admin)
    end

end

app/controllers/contatos_controller.rb
# -*- encoding : utf-8 -*-
class ContatosController < PublicController

  skip_before_action :verify_authenticity_token

  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        @system_notice = Settings['CONTATO.mensagem'].to_s
        @type = 'success'
        Mailer.delay.contato @contato
      else
        @system_notice = "Alguma coisa deu errada.".to_s
      end
        format.js
    end
  end

  private
    # Only allow a trusted parameter "white list" through.
    def contato_params
      params.require(:contato).permit(:mensagem, :remote_ip, :user_agent, :nome, :telefone, :email, :capital_disponivel, :cidade, :origem)
    end

end

app/views/a/contatos/_form.html.erb
<%= simple_form_for [:a, @contato] do |f| %>

  <div id="form_error">
    <%= render '/template/form_error', object: @contato %>
  </div>

  <div class="row">
    <div class="col-xs-12">

      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <%= f.input :nome, label: 'Nome', input_html: {placeholder: 'Nome'} %>
        </div>
        <div class="col-xs-12 col-sm-6">
          <%= f.input :email, label: 'E-mail', input_html: {placeholder: 'E-mail'}, as: :email %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <%= f.input :telefone, label: 'Telefone', input_html: {placeholder: 'Telefone', onkeypress: "mascara(this, checaTelefone)", maxlength: 15} %>
        </div>
        <div class="col-xs-12 col-sm-6">
          <%= f.input :celular, label: 'Celular', input_html: {placeholder: 'Celular', onkeypress: "mascara(this, checaTelefone)", maxlength: 15} %>
        </div>
      </div>
      <%= f.input :mensagem, label: 'Mensagem', input_html: {placeholder: 'Mensagem'} %>

    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-xs-12">
      <div class="form-group text-right">
        <%= f.button :submit, 'Enviar', class: "btn btn-primary btn-botao" %>
      </div>
    </div>
  </div>

<% end %>

app/views/a/contatos/_list.html.erb
<div class="table-responsive">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>Capital</th>
        <th>Cidade</th>
        <th>Origem</th>
        <th>IP de Origem</th>
        <th>Enviado em:</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @contatos.each do |contato| %>
        <tr <%= contato.lido_em.nil? ? "class=success" : nil %>>
          <td>
            <%= link_to "#{contato.nome}", a_contato_path(contato), data: { toggle: 'modal', target: '#modal-element-contato', size: :lg  }, class: 'btn btn-xs btn-default' %>
          </td>
          <td><%= contato.email %></td>
          <td><%= contato.telefone %></td>
          <td><%= contato.capital_disponivel %></td>
          <td><%= contato.cidade %></td>
          <td><%= contato.origem %></td>
          <td><%= contato.remote_ip %></td>
          <td><%= l contato.created_at, format: :short %></td>
          <td>
            <% if can? :destroy, contato  %>
              <%= link_to "#{glyph('remove', {tag: :i})} ".html_safe + t('helpers.links.destroy'),
                          a_contato_path(contato),
                          method: :delete,
                          remote: true,
                          data: { confirm: t('helpers.links.confirm_delete', model: "Contato") },
                          class: 'btn btn-xs btn-danger' %>
            <% end %>
            <% if can? :edit, contato %>
                <%= link_to "#{glyph('edit', {tag: :i})} Editar".html_safe, edit_a_contato_path(contato), class: 'btn btn-xs btn-default', title: "Editar Contato" %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <tr>
        <td colspan="10"><%= pagination_footer @contatos %></td>
      </tr>

    </tbody>
  </table>

</div>

app/views/a/contatos/_list_facebook.html.erb
<div class="table-responsive">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>IP de Origem</th>
        <th>Enviado em:</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @contatos.each do |contato| %>
        <tr <%= contato.lido_em.nil? ? "class=success" : nil %>>
          <td>
            <%= link_to "#{contato.nome}", a_contato_path(contato), data: { toggle: 'modal', target: '#modal-element-contato', size: :lg  }, class: 'btn btn-xs btn-default' %>
          </td>
          <td><%= contato.email %></td>
          <td><%= contato.telefone %></td>
          <td><%= contato.remote_ip %></td>
          <td><%= l contato.created_at, format: :short %></td>
          <td>
            <% if can? :destroy, contato  %>
              <%= link_to "#{glyph('remove', {tag: :i})} ".html_safe + t('helpers.links.destroy'),
                          a_contato_path(contato),
                          method: :delete,
                          remote: true,
                          data: { confirm: t('helpers.links.confirm_delete', model: "Contato") },
                          class: 'btn btn-xs btn-danger' %>
            <% end %>
            <% if can? :edit, contato %>
                <%= link_to "#{glyph('edit', {tag: :i})} Editar".html_safe, edit_a_contato_path(contato), class: 'btn btn-xs btn-default', title: "Editar Contato" %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <tr>
        <td colspan="10"><%= pagination_footer @contatos %></td>
      </tr>

    </tbody>
  </table>

</div>

app/views/a/contatos/edit.html.erb
<% content_for(:title, t('helpers.titles.edit', model: 'Contato')) %>
<div class="container-fluid">

  <div class="page-header">
    <h3><%= t('helpers.titles.edit', model: 'Contato') %> # <%= "#{@contato.id}"%></h3>
  </div>
  <%= render partial: 'form' %>
</div>

<%= javascript_tag do %>
  $(function() {
    $('#modal-element-contato').on('hidden.bs.modal', function (e) {
      $('#contatos_filter_form').submit();
      $(this).removeData('bs.modal');
    });
  });
<% end %>

app/views/a/contatos/facebook.html.erb
<% content_for(:title, 'Leads') %>

<div class="modal fade" id="modal-element-contato" tabindex="-1" role="dialog" aria-labelledby="modal-element-contato-label" aria-hidden="true">
  <div class="modal-dialog" id="modal-element-contato-dialog">
    <div class="modal-content" id="modal-element-contato-content"></div>
  </div>
</div>

        <div id="chart_div2" style="width: 100%; height: 400px;"></div>
<div class="page-header">
  <h3><%= 'Leads' %></h3>
</div>
        
<div class="row">
  <div class="col-sm-12 col-xs-12">
    <%= simple_form_for a_contatos_path, method: :get, url: a_contatos_path, remote: true, html: {id: :contatos_filter_form} do |f| %>

<div class="row">
  <div class="col-md-3">
      <%= f.input :nome, label: false, required: false, input_html: {name: :nome, placeholder: 'Nome do Cliente'} %>
  </div>
  <div class="col-md-3">
      <%= f.input :email, label: false, required: false, input_html: {name: :email, placeholder: 'E-mail'} %>
  </div>
  <div class="col-md-3">
      <div class="form-group">
        <%= f.button :submit, t('helpers.links.search'), class: "btn btn-primary" %>
      </div>
  </div>
</div>
    <% end %>
  </div>
</div>



<div class="row">

  <div class="col-sm-12 col-xs-12">
    <div id="contatos_list">
      <%= render 'list_facebook' %>
    </div>
  </div>

</div>


<script type="text/javascript">
  $(function () {
  $('[data-toggle="popover"]').popover()
})
</script>


<script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawVisualization);

      function drawVisualization() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable([
         <%= "#{['Dia']+['Leads']+['Quantidade']}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-6.day), format: '%A'))]+[Contato.media_dia(Date.today-6.day)]+[Contato.media_dia(Date.today-6.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-5.day), format: '%A'))]+[Contato.media_dia(Date.today-5.day)]+[Contato.media_dia(Date.today-5.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-4.day), format: '%A'))]+[Contato.media_dia(Date.today-4.day)]+[Contato.media_dia(Date.today-4.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-3.day), format: '%A'))]+[Contato.media_dia(Date.today-3.day)]+[Contato.media_dia(Date.today-3.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-2.day), format: '%A'))]+[Contato.media_dia(Date.today-2.day)]+[Contato.media_dia(Date.today-2.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-1.day), format: '%A'))]+[Contato.media_dia(Date.today-1.day)]+[Contato.media_dia(Date.today-1.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today), format: '%A'))]+[Contato.media_dia(Date.today)]+[Contato.media_dia(Date.today)]}".html_safe %>,
      ]);

    var options = {
      title : 'Cadastros / Dia',
      vAxis: {title: 'Cadastros'},
      hAxis: {title: 'Dia'},
      seriesType: 'bars',
      series: {1: {type: 'line'}}
    };

    var chart = new google.visualization.ComboChart(document.getElementById('chart_div2'));
    chart.draw(data, options);
  }
    </script>

app/views/a/contatos/facebook.js.erb
$("#contatos_list").html("<%= j( render 'list_facebook' )%>");
<% unless @system_notice.blank? %>
  $('#alert').html("<%= j( render '/template/alert', notice: @system_notice, type: @type )%>");
<% end %>

app/views/a/contatos/index.html.erb
<% content_for(:title, 'Leads') %>

<div class="modal fade" id="modal-element-contato" tabindex="-1" role="dialog" aria-labelledby="modal-element-contato-label" aria-hidden="true">
  <div class="modal-dialog" id="modal-element-contato-dialog">
    <div class="modal-content" id="modal-element-contato-content"></div>
  </div>
</div>

        <div id="chart_div2" style="width: 100%; height: 400px;"></div>
<div class="page-header">
  <h3><%= 'Leads' %></h3>
</div>
        
<div class="row">
  <div class="col-sm-12 col-xs-12">
    <%= simple_form_for a_contatos_path, method: :get, url: a_contatos_path, remote: true, html: {id: :contatos_filter_form} do |f| %>

<div class="row">
  <div class="col-md-3">
      <%= f.input :nome, label: false, required: false, input_html: {name: :nome, placeholder: 'Nome do Cliente'} %>
  </div>
  <div class="col-md-3">
      <%= f.input :email, label: false, required: false, input_html: {name: :email, placeholder: 'E-mail'} %>
  </div>
  <div class="col-md-3">
      <div class="form-group">
        <%= f.button :submit, t('helpers.links.search'), class: "btn btn-primary" %>
      </div>
  </div>
</div>
    <% end %>
  </div>
</div>



<div class="row">

  <div class="col-sm-12 col-xs-12">
    <div id="contatos_list">
      <%= render 'list' %>
    </div>
  </div>

</div>


<script type="text/javascript">
  $(function () {
  $('[data-toggle="popover"]').popover()
})
</script>


<script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawVisualization);

      function drawVisualization() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable([
         <%= "#{['Dia']+['Leads']+['Quantidade']}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-6.day), format: '%A'))]+[Contato.media_dia(Date.today-6.day)]+[Contato.media_dia(Date.today-6.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-5.day), format: '%A'))]+[Contato.media_dia(Date.today-5.day)]+[Contato.media_dia(Date.today-5.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-4.day), format: '%A'))]+[Contato.media_dia(Date.today-4.day)]+[Contato.media_dia(Date.today-4.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-3.day), format: '%A'))]+[Contato.media_dia(Date.today-3.day)]+[Contato.media_dia(Date.today-3.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-2.day), format: '%A'))]+[Contato.media_dia(Date.today-2.day)]+[Contato.media_dia(Date.today-2.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today-1.day), format: '%A'))]+[Contato.media_dia(Date.today-1.day)]+[Contato.media_dia(Date.today-1.day)]}".html_safe %>,
         <%= "#{[(I18n.l((Date.today), format: '%A'))]+[Contato.media_dia(Date.today)]+[Contato.media_dia(Date.today)]}".html_safe %>,
      ]);

    var options = {
      title : 'Cadastros / Dia',
      vAxis: {title: 'Cadastros'},
      hAxis: {title: 'Dia'},
      seriesType: 'bars',
      series: {1: {type: 'line'}}
    };

    var chart = new google.visualization.ComboChart(document.getElementById('chart_div2'));
    chart.draw(data, options);
  }
    </script>

app/views/a/contatos/index.js.erb
$("#contatos_list").html("<%= j( render 'list' )%>");
<% unless @system_notice.blank? %>
  $('#alert').html("<%= j( render '/template/alert', notice: @system_notice, type: @type )%>");
<% end %>