config/routes.rb
# -*- encoding : utf-8 -*-

require 'api_constraints'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  #########################################
  ############## Aplicação ################
  #########################################
  namespace :a do
    devise_for :usuarios, class_name: "Usuario", controllers: { sessions: 'a/usuarios/sessions',
                                                                passwords: 'a/usuarios/passwords',
                                                                registrations: 'a/usuarios'  }
    controller :usuarios do
      get "usuarios/alterar_senha" => :alterar_senha
      post "usuarios/salvar_senha" => :salvar_senha
    end
    resources :usuarios

    controller :contatos do
      get '/contatos/facebook' => :facebook, as: :contatos_facebook
    end
    resources :contatos


    controller :configuracoes do
      get '/configuracoes/gerais' => :gerais, as: :configuracoes_gerais
      post '/configuracoes/gerais_salvar' => :gerais_salvar, as: :configuracoes_gerais_salvar
      get '/configuracoes/sobre' => :sobre, as: :configuracoes_sobre
      post '/configuracoes/sobre_salvar' => :sobre_salvar, as: :configuracoes_sobre_salvar
      get 'configuracoes/gerar_api_token' => :gerar_api_token
    end

    root "contatos#index"
  end

  #########################################
  ################ Public #################
  #########################################

  controller :contatos do
  end
  resources :contatos

  controller :pages do
    get '/home' => :home
  end

  root "pages#home"

  #########################################
  ################# API ###################
  #########################################
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      controller :sync do
        get 'sync' => :sync
      end

    end
  end

end

app/controllers/a/app_controller.rb
# -*- encoding : utf-8 -*-
class A::AppController < ApplicationController

  before_action :authenticate_a_usuario!
  before_filter :guardar_per_page

  check_authorization
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: I18n.t('login.access_denied')
  end

  # Define o usuario a ser tertado no ability.rb
  def current_ability
    @current_ability ||= Ability.new(current_a_usuario)
  end

  private
    #
    # Uma vez que se altere o per_page, ele vai pra sessão.
    # Isso facilita buscas globais e não perde o per_page em listas com filtros.
    def guardar_per_page
      if params[:per_page].blank?
        params[:per_page] = session[:per_page]
      else
        session[:per_page] = params[:per_page]
      end
    end

end

app/controllers/a/configuracoes_controller.rb
# -*- encoding : utf-8 -*-
class A::ConfiguracoesController < A::AppController

  skip_authorization_check
  skip_load_and_authorize_resource

  before_filter :garantir_autorizacao



  def gerais_salvar

    # CONFIGURACOES
    Settings['CONFIGURACOES.title']                                 = params[:title]
    Settings['CONFIGURACOES.logo']                                  = params[:logo]
    Settings['CONFIGURACOES.logo2']                                 = params[:logo2]
    Settings['CONFIGURACOES.logo_after']                            = params[:logo_after]
    Settings['CONFIGURACOES.logo2_after']                           = params[:logo2_after]

    # CONTATO
    Settings['CONTATO.telefone']            = params[:telefone]
    Settings['CONTATO.email']               = params[:email]
    Settings['CONTATO.mensagem']            = params[:mensagem]
    Settings['CONTATO.endereco']            = params[:endereco]
    Settings['CONTATO.atendimento_online']  = params[:atendimento_online]
    Settings['CONTATO.mapa_iframe']         = params[:mapa_iframe]

    # REDE_SOCIAIS
    Settings['REDE_SOCIAIS.site']       = params[:site]
    Settings['REDE_SOCIAIS.facebook']   = params[:facebook]

    @system_notice = I18n.t('configuracoes.salvou')
    @type = 'success'

    redirect_to a_configuracoes_gerais_path, notice: @system_notice
  end

  def gerar_api_token
    ApiKey.first.destroy
    ApiKey.create!

    respond_to do |format|
      format.js
    end
  end

  private

    def garantir_autorizacao
      authorize! :configurar, :sistema
    end

end

app/controllers/a/contatos_controller.rb
# -*- encoding : utf-8 -*-
class A::ContatosController < A::AppController

  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  def index
    conditions = []
    conditions << "contatos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "contatos.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    conditions << "contatos.pre_cadastro IS NULL"

    @contatos = Contato.where(conditions.join(' AND ')).ordenados.paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @contatos.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('contatos.contatos'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contatos
  def facebook
    conditions = []
    conditions << "contatos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "contatos.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    @contatos = Contato.where(conditions.join(' AND ')).where(pre_cadastro: true).ordenados.paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @contatos.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('contatos.contatos'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contatos/1
  def show
    @reduzir = false
    if @contato.lido_em.nil?
      @contato.lido_em = Time.zone.now
      @contato.save(:validate => false)
      @reduzir = true
    end
    render layout: false
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # contato /contatos
  def create
    @contato = Contato.new(contato_params)

    if @contato.save
      redirect_to a_contatos_path, notice: "Contato Criado!"
    else
      render :new
    end
  end

  # PATCH/PUT /contatos/1
  def update

    if @contato.update(contato_params)
      redirect_to a_contatos_path, notice: "Contato Atualizado!"
    else
      render :edit
    end
  end

  # DELETE /contatos/1
  def destroy
    @contato.destroy
    redirect_to a_contatos_url, notice: notice
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contato_params
      params.require(:contato).permit(:nome, :telefone, :email, :mensagem, :capital_disponivel, :cidade, :origem)
    end

end

app/controllers/a/usuarios/passwords_controller.rb
# -*- encoding : utf-8 -*-
class A::Usuarios::PasswordsController < Devise::PasswordsController

  # layout false, only: [:new, :create]
  # layout 'site', only: [:edit, :update]

  layout :layout_by_resource

  protected

  def after_sending_reset_password_instructions_path_for(resource_name)
    new_a_usuario_session_path
  end

  def layout_by_resource
    if devise_controller? && (action_name == "new" or action_name == "create")
      false
    else
      "application"
    end
  end

end

app/controllers/a/usuarios/sessions_controller.rb
# -*- encoding : utf-8 -*-
class A::Usuarios::SessionsController < Devise::SessionsController
end

app/controllers/a/usuarios_controller.rb
# -*- encoding : utf-8 -*-
class A::UsuariosController < A::AppController

  before_action :set_usuario, only: [:show, :edit, :update, :destroy, :alterar_senha]

  # GET /usuarios
  def index
    conditions = []
    conditions << "usuarios.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "usuarios.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    params[:ativos] = true if params[:ativos].blank?
    conditions << "usuarios.ativo = #{params[:ativos]}"

    @usuarios = Usuario.where(conditions.join(' AND ')).order("nome ASC").paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @usuarios.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('usuarios.usuarios'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /usuarios/1
  def show
    render layout: false
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # usuario /usuarios
  def create
    @usuario = Usuario.new(usuario_params)

    if @usuario.save
      redirect_to a_usuarios_path, notice: I18n.t('action_controller.adicionado', model: I18n.t('usuarios.usuario'))
    else
      render :new
    end
  end

  # PATCH/PUT /usuarios/1
  def update

    # Se o password não foi preenchido, não atualiza
    if params[:usuario][:password].blank?
      params[:usuario].delete :password
      params[:usuario].delete :password_confirmation
    end

    if @usuario.update(usuario_params)
      redirect_to a_usuarios_path, notice: I18n.t('action_controller.atualizado', model: I18n.t('usuarios.usuario'))
    else
      render :edit
    end
  end

  # DELETE /usuarios/1
  def destroy
    @usuario.alterar!
    @usuario.ativo? ? (notice = I18n.t('action_controller.ativado', model: I18n.t('usuarios.usuario'))) : (notice = I18n.t('action_controller.desativado', model: I18n.t('usuarios.usuario')))
    redirect_to a_usuarios_url, notice: notice
  end

  def alterar_senha
    render layout: false
  end

  def salvar_senha
    @usuario = current_a_usuario

    senha_valida = @usuario.valid_password? params[:usuario][:password_atual]
    @usuario.errors.add(:password_atual, I18n.t('usuarios.password_invalida')) unless senha_valida

    respond_to do |format|
      if senha_valida and @usuario.update(usuario_params)
        sign_in(current_a_usuario, bypass: true)
        @system_notice = I18n.t('action_controller.atualizada', model: I18n.t('usuarios.password'))
        @type = 'info'
        format.js
      else
        format.js
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def usuario_params
      params.require(:usuario).permit(:nome, :telefone, :celular, :email, :password, :password_confirmation, :ativo, :super_admin)
    end

end

app/views/a/configuracoes/gerais.html.erb
<% content_for(:title, 'Configurações') %>

<div class="page-header">
  <h3>Configurações Gerais</h3>
</div>

<div class="row">

  <div class="col-xs-12">
    <%= simple_form_for a_configuracoes_gerais_salvar_path, method: :post, url: a_configuracoes_gerais_salvar_path do |f| %>

      <div class="row">
        <div class="col-xs-12 col-sm-3">
          <div class="page-header">
            <h4>SEO</h4>
          </div>
          <%= f.input :title,
                      label: 'Título do Site',
                      required: true,
                      input_html: {name: :title, value: Settings['CONFIGURACOES.title']} %>
          <%= f.input :logo,
                      label: 'Link do Primeiro Logo',
                      required: true,
                      input_html: {name: :logo, value: Settings['CONFIGURACOES.logo']}, hint: "Usar como Default: /logo.png - Tamanho - 250x100" %>
          <%= f.input :logo_after,
                      label: 'Link do Primeiro Logo - After',
                      required: true,
                      input_html: {name: :logo_after, value: Settings['CONFIGURACOES.logo_after']}, hint: "Usar como Default: /logo.png - Tamanho - 250x100" %>

        </div>

        <div class="col-xs-12 col-sm-3">
          <div class="page-header">
            <h4>Contato</h4>
          </div>
          <div class="row">
            <div class="col-xs-12 col-sm-12">
              <%= f.input :telefone,
                          as: :string,
                          label: 'Telefone de Atendimento',
                          required: true,
                          input_html: {name: :telefone, value: Settings['CONTATO.telefone'], onkeypress: "mascara(this, checaTelefone)", maxlength: 15} %>
              <%= f.input :email,
                          as: :email,
                          label: 'E-mail de Contato',
                          required: true,
                          input_html: {name: :email, value: Settings['CONTATO.email']} %>
              <%= f.input :mensagem,
                          label: 'Mensagem de confirmação de envio',
                          required: true,
                          input_html: {name: :mensagem, value: Settings['CONTATO.mensagem']} %>
              <%= f.input :endereco,
                          as: :ckeditor,
                          label: 'Endereço',
                          required: true,
                          input_html: {name: :endereco, value: Settings['CONTATO.endereco']} %>
              <%= f.input :atendimento_online,
                          as: :url,
                          label: 'Link para Atendimento Online',
                          required: false,
                          input_html: {name: :atendimento_online, value: Settings['CONTATO.atendimento_online']} %>
              <%= f.input :mapa_iframe,
                          as: :text,
                          label: 'Incorporar Google Maps',
                          required: false,
                          hint: 'Adicionar o <iframe>, deixei o height com 350 e width em 100%.',
                          input_html: {name: :mapa_iframe, value: Settings['CONTATO.mapa_iframe']} %>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-sm-3">
          <div class="page-header">
            <h4>Redes Sociais</h4>
          </div>
          <%= f.input :site,
                      as: :url,
                      label: 'Link para Site',
                      required: false,
                      hint: 'Utilizar o link completo com http://',
                      input_html: {name: :site, value: Settings['REDE_SOCIAIS.site']} %>
          <%= f.input :facebook,
                      as: :url,
                      label: 'Link para Facebook',
                      required: false,
                      hint: 'Utilizar o link completo com http://',
                      input_html: {name: :facebook, value: Settings['REDE_SOCIAIS.facebook']} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.button :submit, "Salvar", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>



<%= javascript_include_tag 'ckeditor/ckeditor.js' %>

app/views/a/configuracoes/gerar_api_token.js.erb
$('input#api_key').val("<%= ApiKey.first.access_token %>");