config/routes.rb
# -*- encoding : utf-8 -*-

require 'api_constraints'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  #########################################
  ############## Aplicação ################
  #########################################
  namespace :a do
    devise_for :usuarios, class_name: "Usuario", controllers: { sessions: 'a/usuarios/sessions',
                                                                passwords: 'a/usuarios/passwords',
                                                                registrations: 'a/usuarios'  }
    controller :usuarios do
      get "usuarios/alterar_senha" => :alterar_senha
      post "usuarios/salvar_senha" => :salvar_senha
    end
    resources :usuarios

    controller :contatos do
      get '/contatos/facebook' => :facebook, as: :contatos_facebook
    end
    resources :contatos


    controller :configuracoes do
      get '/configuracoes/gerais' => :gerais, as: :configuracoes_gerais
      post '/configuracoes/gerais_salvar' => :gerais_salvar, as: :configuracoes_gerais_salvar
      get '/configuracoes/sobre' => :sobre, as: :configuracoes_sobre
      post '/configuracoes/sobre_salvar' => :sobre_salvar, as: :configuracoes_sobre_salvar
      get 'configuracoes/gerar_api_token' => :gerar_api_token
    end

    root "contatos#index"
  end

  #########################################
  ################ Public #################
  #########################################

  controller :contatos do
  end
  resources :contatos

  controller :pages do
    get '/home' => :home
  end

  root "pages#home"

  #########################################
  ################# API ###################
  #########################################
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      controller :sync do
        get 'sync' => :sync
      end

    end
  end

end

app/models/usuario.rb
# -*- encoding : utf-8 -*-
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :async, :registerable, :recoverable, :rememberable, :trackable, :validatable, :session_limitable


  # Atributo utilizado para verificar se a senha atual informada está correta
  attr_accessor :password_atual

  validates :email, :nome, presence: true
  validates :email, uniqueness: true


  scope :ordenados, -> {order('usuarios.nome ASC')}
  scope :ativos, -> {where('usuarios.ativo = ?', true)}

  def to_param
    "#{id} #{nome}".parameterize
  end

  # Bloqueia usuários inativos
  def active_for_authentication?
    super and self.ativo
  end

  # Troca o parametro ativo
  def alterar!
    self.update(ativo: !self.ativo)
  end

  def ativo?
    return self.ativo
  end

  def super_admin?
    return self.super_admin
  end

  def self.to_select
    Usuario.ativos.ordenados.collect { |u| [u.nome, u.id] }
  end

  def nome_completo
    "#{self.id} - #{self.nome}"
  end

  def ultimo_login
    return "Nunca logou" if last_sign_in_at.blank?
    retorno = ""
    retorno << "#{I18n.l last_sign_in_at, format: :short}"
    retorno << " - "
    retorno << "#{last_sign_in_ip}"
  end

end

app/controllers/a/app_controller.rb
# -*- encoding : utf-8 -*-
class A::AppController < ApplicationController

  before_action :authenticate_a_usuario!
  before_filter :guardar_per_page

  check_authorization
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: I18n.t('login.access_denied')
  end

  # Define o usuario a ser tertado no ability.rb
  def current_ability
    @current_ability ||= Ability.new(current_a_usuario)
  end

  private
    #
    # Uma vez que se altere o per_page, ele vai pra sessão.
    # Isso facilita buscas globais e não perde o per_page em listas com filtros.
    def guardar_per_page
      if params[:per_page].blank?
        params[:per_page] = session[:per_page]
      else
        session[:per_page] = params[:per_page]
      end
    end

end

app/controllers/a/configuracoes_controller.rb
# -*- encoding : utf-8 -*-
class A::ConfiguracoesController < A::AppController

  skip_authorization_check
  skip_load_and_authorize_resource

  before_filter :garantir_autorizacao



  def gerais_salvar

    # CONFIGURACOES
    Settings['CONFIGURACOES.title']                                 = params[:title]
    Settings['CONFIGURACOES.logo']                                  = params[:logo]
    Settings['CONFIGURACOES.logo2']                                 = params[:logo2]
    Settings['CONFIGURACOES.logo_after']                            = params[:logo_after]
    Settings['CONFIGURACOES.logo2_after']                           = params[:logo2_after]

    # CONTATO
    Settings['CONTATO.telefone']            = params[:telefone]
    Settings['CONTATO.email']               = params[:email]
    Settings['CONTATO.mensagem']            = params[:mensagem]
    Settings['CONTATO.endereco']            = params[:endereco]
    Settings['CONTATO.atendimento_online']  = params[:atendimento_online]
    Settings['CONTATO.mapa_iframe']         = params[:mapa_iframe]

    # REDE_SOCIAIS
    Settings['REDE_SOCIAIS.site']       = params[:site]
    Settings['REDE_SOCIAIS.facebook']   = params[:facebook]

    @system_notice = I18n.t('configuracoes.salvou')
    @type = 'success'

    redirect_to a_configuracoes_gerais_path, notice: @system_notice
  end

  def gerar_api_token
    ApiKey.first.destroy
    ApiKey.create!

    respond_to do |format|
      format.js
    end
  end

  private

    def garantir_autorizacao
      authorize! :configurar, :sistema
    end

end

app/controllers/a/contatos_controller.rb
# -*- encoding : utf-8 -*-
class A::ContatosController < A::AppController

  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  def index
    conditions = []
    conditions << "contatos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "contatos.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    conditions << "contatos.pre_cadastro IS NULL"

    @contatos = Contato.where(conditions.join(' AND ')).ordenados.paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @contatos.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('contatos.contatos'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contatos
  def facebook
    conditions = []
    conditions << "contatos.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "contatos.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    @contatos = Contato.where(conditions.join(' AND ')).where(pre_cadastro: true).ordenados.paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @contatos.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('contatos.contatos'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contatos/1
  def show
    @reduzir = false
    if @contato.lido_em.nil?
      @contato.lido_em = Time.zone.now
      @contato.save(:validate => false)
      @reduzir = true
    end
    render layout: false
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # contato /contatos
  def create
    @contato = Contato.new(contato_params)

    if @contato.save
      redirect_to a_contatos_path, notice: "Contato Criado!"
    else
      render :new
    end
  end

  # PATCH/PUT /contatos/1
  def update

    if @contato.update(contato_params)
      redirect_to a_contatos_path, notice: "Contato Atualizado!"
    else
      render :edit
    end
  end

  # DELETE /contatos/1
  def destroy
    @contato.destroy
    redirect_to a_contatos_url, notice: notice
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contato_params
      params.require(:contato).permit(:nome, :telefone, :email, :mensagem, :capital_disponivel, :cidade, :origem)
    end

end

app/controllers/a/usuarios/passwords_controller.rb
# -*- encoding : utf-8 -*-
class A::Usuarios::PasswordsController < Devise::PasswordsController

  # layout false, only: [:new, :create]
  # layout 'site', only: [:edit, :update]

  layout :layout_by_resource

  protected

  def after_sending_reset_password_instructions_path_for(resource_name)
    new_a_usuario_session_path
  end

  def layout_by_resource
    if devise_controller? && (action_name == "new" or action_name == "create")
      false
    else
      "application"
    end
  end

end

app/controllers/a/usuarios/sessions_controller.rb
# -*- encoding : utf-8 -*-
class A::Usuarios::SessionsController < Devise::SessionsController
end

app/controllers/a/usuarios_controller.rb
# -*- encoding : utf-8 -*-
class A::UsuariosController < A::AppController

  before_action :set_usuario, only: [:show, :edit, :update, :destroy, :alterar_senha]

  # GET /usuarios
  def index
    conditions = []
    conditions << "usuarios.nome LIKE '%#{params[:nome]}%'" unless params[:nome].blank?
    conditions << "usuarios.email LIKE '%#{params[:email]}%'" unless params[:email].blank?

    params[:ativos] = true if params[:ativos].blank?
    conditions << "usuarios.ativo = #{params[:ativos]}"

    @usuarios = Usuario.where(conditions.join(' AND ')).order("nome ASC").paginate page: params[:page], per_page: params[:per_page]

    # Mensagem para busca vazia
    if params[:commit] == t('helpers.links.search')
      if @usuarios.count.zero?
        @system_notice = I18n.t('action_controller.nao_localizados', model: I18n.t('usuarios.usuarios'))
        @type = 'warning'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /usuarios/1
  def show
    render layout: false
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # usuario /usuarios
  def create
    @usuario = Usuario.new(usuario_params)

    if @usuario.save
      redirect_to a_usuarios_path, notice: I18n.t('action_controller.adicionado', model: I18n.t('usuarios.usuario'))
    else
      render :new
    end
  end

  # PATCH/PUT /usuarios/1
  def update

    # Se o password não foi preenchido, não atualiza
    if params[:usuario][:password].blank?
      params[:usuario].delete :password
      params[:usuario].delete :password_confirmation
    end

    if @usuario.update(usuario_params)
      redirect_to a_usuarios_path, notice: I18n.t('action_controller.atualizado', model: I18n.t('usuarios.usuario'))
    else
      render :edit
    end
  end

  # DELETE /usuarios/1
  def destroy
    @usuario.alterar!
    @usuario.ativo? ? (notice = I18n.t('action_controller.ativado', model: I18n.t('usuarios.usuario'))) : (notice = I18n.t('action_controller.desativado', model: I18n.t('usuarios.usuario')))
    redirect_to a_usuarios_url, notice: notice
  end

  def alterar_senha
    render layout: false
  end

  def salvar_senha
    @usuario = current_a_usuario

    senha_valida = @usuario.valid_password? params[:usuario][:password_atual]
    @usuario.errors.add(:password_atual, I18n.t('usuarios.password_invalida')) unless senha_valida

    respond_to do |format|
      if senha_valida and @usuario.update(usuario_params)
        sign_in(current_a_usuario, bypass: true)
        @system_notice = I18n.t('action_controller.atualizada', model: I18n.t('usuarios.password'))
        @type = 'info'
        format.js
      else
        format.js
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def usuario_params
      params.require(:usuario).permit(:nome, :telefone, :celular, :email, :password, :password_confirmation, :ativo, :super_admin)
    end

end

app/views/a/usuarios/_form.html.erb
<%= simple_form_for [:a, @usuario] do |f| %>

  <%= render '/template/form_error', object: @usuario %>

  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :nome, label: t('usuarios.nome') %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :email, label: t('usuarios.email') %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 col-xs-12">
      <%= f.input :password, label: t('usuarios.password') %>
    </div>
    <div class="col-sm-2 col-xs-12">
      <%= f.input :password_confirmation, label: t('usuarios.password_confirmation') %>
    </div>
    <div class="col-sm-2 col-xs-12">
      <%= f.input :telefone, label: t('usuarios.telefone'), input_html: {onkeypress: "mascara(this, checaTelefone)", maxlength: 15} %>
    </div>
    <div class="col-sm-2 col-xs-12">
      <%= f.input :celular, label: t('usuarios.celular'), input_html: {onkeypress: "mascara(this, checaTelefone)", maxlength: 15} %>
    </div>
    <div class="col-sm-2 col-xs-12">
      <%= f.input :ativo, label: t('usuarios.ativo'), collection: [[t('simple_form.yes'), true], [t('simple_form.no'), false]], include_blank: false %>
    </div>
    <div class="col-sm-2 col-xs-12">
      <%= f.input :super_admin, label: "Admin", collection: [[t('simple_form.yes'), true], [t('simple_form.no'), false]], include_blank: false %>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-12 col-xs-12">
      <div class="form-group">
        <%= f.button :submit, class: "btn btn-primary" %>
        <%= link_to t('.cancel', default: t("helpers.links.cancel")), a_usuarios_path, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>

<% end %>

app/views/a/usuarios/_list.html.erb
<div class="table-responsive">

  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('usuarios.nome') %></th>
        <th><%= t('usuarios.telefone') %></th>
        <th><%= t('usuarios.celular') %></th>
        <th><%= t('usuarios.email') %></th>
        <th><%= t('usuarios.log_data') %></th>
        <th><%=t '.actions', default: t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @usuarios.each do |usuario| %>
        <tr>
          <td>
            <% if can? :show, usuario %>
              <%= link_to "#{glyph('search', {tag: :i})} #{usuario.nome}".html_safe, [:a, usuario], data: { toggle: 'modal', target: '#modal-element' } %>
            <% else %>
              <%= usuario.nome %>
            <% end %>
          </td>
          <td><%= usuario.telefone %></td>
          <td><%= usuario.celular %></td>
          <td><%= usuario.email %></td>
          <td><%= usuario.ultimo_login %></td>
          <td>
            <% if can? :edit, usuario %>
              <%= link_to "#{glyph('pencil', {tag: :i})} ".html_safe + t('helpers.links.edit'),
                          edit_a_usuario_path(usuario),
                          class: 'btn btn-default btn-xs' %>
            <% end %>
            <% if can? :destroy, usuario %>
              <% if usuario.ativo? %>
                <%= link_to "#{glyph('remove', {tag: :i})} ".html_safe + t('helpers.links.desativar'),
                            a_usuario_path(usuario),
                            method: :delete,
                            data: { confirm: t('helpers.links.confirm') },
                            class: 'btn btn-xs btn-danger' %>
              <% else %>
                <%= link_to "#{glyph('ok', {tag: :i})} ".html_safe + t('helpers.links.ativar'),
                            a_usuario_path(usuario),
                            method: :delete,
                            data: { confirm: t('helpers.links.confirm') },
                            class: 'btn btn-xs btn-success' %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <tr>
        <td colspan="8"><%= pagination_footer @usuarios %></td>
      </tr>

    </tbody>
  </table>

</div>

app/views/a/usuarios/alterar_senha.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only">Close</span>
  </button>
  <h4 class="modal-title" id="modal_element_label"><%= t('usuarios.password_change', nome: @usuario.nome).html_safe %></h4>
</div>

<%= simple_form_for [:a, @usuario], url: a_usuarios_salvar_senha_path, method: :post, remote: true do |f| %>

  <div class="modal-body">
    <div id="form_error">
      <%= render '/template/form_error', object: @usuario %>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= f.input :password_atual, label: t('usuarios.password_atual'), required: true %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= f.input :password, label: t('usuarios.password_new'), required: true %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= f.input :password_confirmation, label: t('usuarios.password_confirmation'), required: true %>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <div class="row">
      <div class="col-xs-12">
        <div class="form-group">
          <%= f.button :submit, t('usuarios.password_change_save'), class: "btn btn-primary" %>
          <%= link_to t('.cancel', default: t("helpers.links.cancel")), "javascript:void(0)", class: 'btn btn-danger', data: {dismiss: 'modal'} %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/a/usuarios/edit.html.erb
<% content_for(:title, t('helpers.titles.edit', model: t('usuarios.usuario'))) %>

<div class="page-header">
  <h3><%= t('helpers.titles.edit', model: t('usuarios.usuario')) %> # <%= @usuario.id %></h3>
</div>
<%= render partial: 'form' %>

app/views/a/usuarios/index.html.erb
<% content_for(:title, t('usuarios.index')) %>

<div class="page-header">
  <h3><%= t('usuarios.index') %></h3>
</div>

<div class="row">

    <%= simple_form_for a_usuarios_path, method: :get, url: a_usuarios_path, remote: true do |f| %>
  <div class="col-md-3 col-sm-3 col-xs-12">
      <%= f.input :nome, label: false, required: false, input_html: {name: :nome, placeholder: 'Nome'} %>
  </div>
  <div class="col-md-3 col-sm-3 col-xs-12">
      <%= f.input :email, label: false, required: false, input_html: {name: :email, placeholder: 'E-mail'} %>
  </div>
  <div class="col-md-3 col-sm-3 col-xs-12">
      <%= f.input :ativos, label: false, required: false, collection: [[t('simple_form.yes'), true], [t('simple_form.no'), false]], input_html: {name: :ativos}, include_blank: false, hint: "Ativos" %>
  </div>
  <div class="col-md-3 col-sm-3 col-xs-12">
    <div class="row">
      <div class="col-md-3 col-sm-3 col-xs-12">
        <div class="form-group">
          <%= f.button :submit, t('helpers.links.search'), class: "btn btn-primary" %>
        </div>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12">
        <% if can? :create, Usuario %>
          <div class="form-group">
            <%= link_to "#{glyph('plus', {tag: :i})} #{t('action_controller.adicionar', model: t('usuarios.usuario'))}".html_safe, new_a_usuario_path, class: 'btn btn-success btn-sm' %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12 col-xs-12">
    <div id="usuarios_list">
      <%= render 'list' %>
    </div>
  </div>

</div>

app/views/a/usuarios/index.js.erb
$("#usuarios_list").html("<%= j( render 'list' )%>");
<% unless @system_notice.blank? %>
  $('#alert').html("<%= j( render '/template/alert', notice: @system_notice, type: @type )%>");
<% end %>

app/views/a/usuarios/new.html.erb
<% content_for(:title, t('action_controller.adicionar', model: t('usuarios.usuario'))) %>

<div class="page-header">
  <h3><%= t('action_controller.adicionar', model: t('usuarios.usuario')) %></h3>
</div>
<%= render partial: 'form' %>

app/views/a/usuarios/salvar_senha.js.erb
<% if @usuario.errors.any? %>
  $("#form_error").html("<%= j( render '/template/form_error', object: @usuario )%>");
<% else %>
  $("#modal-element").modal("hide");
  <% unless @system_notice.blank? %>
    $('#alert').html("<%= j( render '/template/alert', notice: @system_notice, type: @type )%>");
  <% end %>
<% end %>

app/views/a/usuarios/show.html.erb
<div class="modal-header">
 <button type="button" class="close" data-dismiss="modal">
   <span aria-hidden="true">&times;</span>
   <span class="sr-only">Close</span>
 </button>
 <h4 class="modal-title" id="modal_element_label"><strong><%= t('usuarios.usuario') %>: </strong><%= @usuario.nome %></h4>
</div>

<div class="modal-body">
  <ul class="list-group">
    <li class="list-group-item">
      <strong><%= t('usuarios.email') %>: </strong><%= @usuario.email %>
    </li>
    <li class="list-group-item">
      <strong><%= t('usuarios.telefone') %>: </strong><%= @usuario.telefone %>
    </li>
    <li class="list-group-item">
      <strong><%= t('usuarios.celular') %>: </strong><%= @usuario.celular %>
    </li>
    <% unless @usuario.endereco.blank? %>
      <li class="list-group-item">
        <strong>Endereço: </strong><%= @usuario.endereco.nome_completo %>
      </li>
    <% end %>
  </ul>
</div>